Repository laminas/laminas-permissions-acl, pull requests merged in 2021-04, with the labels that each got.

#15 Add GHA CI workflow
  .gitattributes
  .github/workflows/continuous-integration.yml
  .gitignore
  .laminas-ci.json
  .travis.yml
  CHANGELOG.md
  README.md
  composer.json
  composer.lock
Labels: Enhancement

#14 Updated for phpunit 9 and php8
  composer.json
  composer.lock
  src/Assertion/AssertionManager.php
  test/AclTest.php
  test/Assertion/AssertionAggregateTest.php
  test/Assertion/AssertionManagerTest.php
  test/Assertion/CallbackAssertionTest.php
  test/Assertion/ExpressionAssertionTest.php
  test/Assertion/TestSubclasses/AssertionAggregate.php
  test/Assertion/TestSubclasses/CallbackAssertion.php
Labels: Awaiting Author Updates, Enhancement

#17 bugfix: order of document headers is not properly aligned
  docs/book/ownership.md
Labels: Documentation
